"""Frozen rules; no outcome-dependent parameter search."""
from datetime import datetime, timezone

RULE_IDS = ("A_exact_payoff_basket", "B_official_source_carry")
COST_MULTIPLIERS = (1.0, 2.0)
CAPITAL = 10_000.0
VENUE_CAPITAL = 5_000.0
MAX_LOCKED_FRACTION = 0.50
MAX_FAMILY_FRACTION = 0.05
TARGET_UNITS = 100.0
LEVEL_PARTICIPATION = 0.10
MIN_NET_EDGE = 0.02
MAX_BOOK_AGE_S = 2.0
MAX_LEG_SKEW_S = 1.0
MAX_VENUE_LAG_S = 2.0
CONFIRM_MIN_GAP_S = 2.0
LEG_LATENCY_S = 1.0
MAX_EXECUTION_WAIT_S = 2.0
SOURCE_ENTRY_DELAY_S = 60.0
FUNDING_RATE = 0.10
PROJECTED_RELEASE_DELAY_DAYS = 30
MAX_A_DEADLINE_DAYS = 7
OOS_FRACTION = 0.20
ANNUAL_DAYS = 365
MIN_OOS_ENTRY_DATES = 30
MIN_OOS_DAILY_OBS = 60
TARGET_SHARPE = 1.5
BOOT_DRAWS = 2_000
BOOT_SEED = 7301
PROSPECTIVE_START = datetime(2026, 10, 5, tzinfo=timezone.utc)
ALLOW_NETWORK_DATA_PULLS = False
ALLOW_PROTECTED_FORWARD = False
ALLOW_MID_PRICE_FILL = False
DATA_LABEL = "reused_history_exploratory"
