"""results.csv companions: tests.json, chart.png and SUMMARY.md. Every number in SUMMARY.md is generated from `res`."""
from __future__ import annotations

import json

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from .analysis import usable  # noqa: E402
from .config import CLASSES, PARAMS, RESULTS_DIR  # noqa: E402

CLS_COLOR = {"recession": "#2a78d6", "fed": "#eb6834", "inflation": "#1f9e74", "unemployment": "#8a5cd1", "gdp": "#c7a21a"}
MUTED, GRID = "#52514e", "#e4e3df"


def _f(x, nd=2):
    return "n/a" if x is None or not np.isfinite(x) else f"{x:+.{nd}f}"


def _p(x):
    return "n/a" if x is None or not np.isfinite(x) else ("<0.001" if x < 0.001 else f"{x:.3f}")


def _line(p: dict) -> str:
    return (f"b = {_f(p['b'])} bp per pp [{_f(p['ci'][0])}, {_f(p['ci'][1])}], clustered t = {_f(p['cluster_t'])}, "
            f"date-permutation p = {_p(p['p_perm'])}, HC3 t = {_f(p['hc3_t'])}, n = {p['n']} rows, {p['n_dates']} dates")


def chart(rows: pd.DataFrame, res: dict, path) -> None:
    u = usable(rows)
    fig, ax = plt.subplots(figsize=(8, 5.2))
    for cls in CLASSES:
        sub = u[u["cls"] == cls]
        if not sub.empty:
            ax.scatter(sub["x_pp"], sub["gap_spy_bp"], s=14, alpha=0.6, color=CLS_COLOR[cls], label=f"{cls} ({len(sub)})")
    p = res["primary"]
    if len(u) and np.isfinite(p["b"]):
        xs = np.linspace(u["x_pp"].min(), u["x_pp"].max(), 50)
        ax.plot(xs, p["a"] + p["b"] * xs, color="#0b0b0b", lw=1.4, label=f"pooled b = {p['b']:+.2f} bp/pp")
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.grid(True, color=GRID, lw=0.6)
    ax.set_axisbelow(True)
    ax.tick_params(colors=MUTED, labelsize=8)
    ax.set_xlabel("oriented PM move over the closure (pp)")
    ax.set_ylabel("SPY opening gap (bp)")
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def _jsonable(o):
    if isinstance(o, dict):
        return {str(k): _jsonable(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_jsonable(v) for v in o]
    if isinstance(o, np.ndarray):
        return [_jsonable(v) for v in o.tolist()]
    if isinstance(o, (np.floating, float)):
        return None if not np.isfinite(o) else float(o)
    if isinstance(o, np.integer):
        return int(o)
    return o


def summary(res: dict, cov: pd.DataFrame | None) -> str:
    p, c = res["primary"], res["contrast"]
    L = ["# Overnight-gap relation on a rule-selected US macro panel: results", "",
         "Pre-registered in `research/macro_panel/METHOD.md`. Generated by `macro_panel.report` from `results.csv`.", "",
         "## Primary (T3)", "",
         f"- Sample: {res['n_markets_usable']} markets, {res['n_rows_usable']} usable of {res['n_rows_total']} rows, "
         f"{res['n_dates_usable']} closure dates.",
         f"- Pooled slope: {_line(p)}.",
         f"- **Verdict: {res['verdict']}** (rule: b > 0, date-permutation p < 0.05, clustered t > 2; "
         f"met: {', '.join(k for k, v in res['verdict_detail'].items() if v) or 'none'}).",
         f"- For comparison: original +{res['original']['b']} bp per pp (380 closures), replication "
         f"+{res['replication']['b']} (1,211 rows, clustered t {res['replication']['cluster_t']}).", ""]
    L += ["## Secondary (T1): macro minus geopolitics", ""]
    if c and np.isfinite(c.get("d", np.nan)):
        L += [f"- d = b_macro - b_geo = {_f(c['d'])} bp per pp [{_f(c['ci'][0])}, {_f(c['ci'][1])}] (clustered t "
              f"{_f(c['t'])}, {c['G']} dates); b_macro {_f(c['b_macro'])}, b_geo {_f(c['b_geo'])} "
              f"({c['n_geo']} geopolitical rows from leadlag_replication). **{c['label']}.**", ""]
    else:
        L += ["- not computable", ""]
    s2, sp, col = res["s2"], res["s2_date_perm"], res["collapsed"]
    L += ["## Other secondary results (not in the verdict)", "",
          f"- One observation per date: b = {_f(col['b'])} (HC3 t {_f(col['t'])}, permutation p {_p(col.get('p_perm'))}, n = {col['n']}).",
          f"- Sign test at {PARAMS.theta_pp} pp: {s2['k']} of {s2['n']} agree "
          f"({100 * s2['rate']:.0f}%), binomial p {_p(s2['p'])}, date-permutation p {_p(sp.get('p_perm'))}." if s2["n"] else
          "- Sign test: no rows pass the threshold.",
          f"- Fresh 2023 dates: {_line(res['fresh'])}.",
          f"- Overnight: {_line(res['by_kind']['overnight'])}.",
          f"- Weekend/holiday: {_line(res['by_kind']['weekend_holiday'])}.", "", "By class:", "",
          "| Class | Markets | Rows | b | 95% CI | clustered t | perm p | b without this class |", "|---|---|---|---|---|---|---|---|"]
    for k, v in res["by_class"].items():
        L.append(f"| {k} | {v['n_markets']} | {v['n']} | {_f(v['b'])} | [{_f(v['ci'][0])}, {_f(v['ci'][1])}] | "
                 f"{_f(v['cluster_t'])} | {_p(v['p_perm'])} | {_f(res['loo_class'].get(k))} |")
    L += ["", "Per market:", "", "| Rank | Market | Class | Sign | Rows | b | clustered t |", "|---|---|---|---|---|---|---|"]
    for m, v in sorted(res["per_market"].items(), key=lambda kv: kv[1]["rank"]):
        L.append(f"| {v['rank']} | `{m}` | {v['cls']} | {v['sign']:+d} | {v['n']} | {_f(v['b'])} | {_f(v['cluster_t'])} |")
    if res["excluded"]:
        L += ["", "Excluded rows: " + ", ".join(f"{k} {v}" for k, v in res["excluded"].items()) + "."]
    if cov is not None and len(cov):
        L += ["", f"Selection walk: {int(cov['qualifies'].sum())} of {len(cov)} examined markets passed the "
              f"{PARAMS.min_pm_closures}-closure PM coverage check (`coverage.csv`)."]
    L += ["", "## Caveats", "",
          "- Co-movement over the closure, not a lead: ES/NQ futures and pre-market SPY are not observed here.",
          "- Fed and unemployment signs are fixed ex ante and can flip under 'bad news is good news'.",
          "- Rows on the same date share one gap; the clustered t and the date permutation are the primary inference.",
          "- The geopolitical comparison panel covers 2024-2025 only; the macro panel also covers 2023.", ""]
    return "\n".join(L)


def write_all(rows: pd.DataFrame, res: dict, cov: pd.DataFrame | None, out_dir=None) -> None:
    out = out_dir or RESULTS_DIR
    out.mkdir(parents=True, exist_ok=True)
    (out / "tests.json").write_text(json.dumps(_jsonable(res), indent=1))
    (out / "SUMMARY.md").write_text(summary(res, cov))
    chart(rows, res, out / "chart.png")
